services:
  mffr-profit:
    build:
      context: ./backend
    container_name: mffr-profit
    ports:
      - "8099:8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - TZ=${TZ}
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - SENSOR_MODE=${SENSOR_MODE}
      - SENSOR_POWER=${SENSOR_POWER}
      - SENSOR_GRID=${SENSOR_GRID}
      - SENSOR_NORDPOOL=${SENSOR_NORDPOOL}
      - SENSOR_BASELINE=${SENSOR_BASELINE} 
      - SENSOR_MFFR_POWER=${SENSOR_MFFR_POWER} 
    restart: unless-stopped

  mffr-ui:
    build:
      context: ./frontend
    container_name: mffr-ui
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - mffr_ui_node_modules:/app/node_modules
    depends_on:
      - mffr-profit

volumes:
  mffr_ui_node_modules: