views:
  - title: MFFR
    cards:
      - type: entities
        title: MFFR Status
        entities:
          - entity: sensor.mffr_signal
          - entity: sensor.mffr_power
          - entity: sensor.mffr_slot_profit
          - entity: sensor.mffr_today_profit
          - entity: sensor.mffr_up_count
          - entity: sensor.mffr_down_count

      - type: history-graph
        title: MFFR Power & Profit (24h)
        hours_to_show: 24
        entities:
          - sensor.mffr_power
          - sensor.mffr_slot_profit

      - type: statistics-graph
        title: MFFR Profit Totals
        stat_types:
          - sum
        entities:
          - sensor.mffr_today_profit
          - sensor.mffr_week_profit
          - sensor.mffr_month_profit

      - type: markdown
        content: |
          ## Recent MFFR Activities
          {{ states.sensor.mffr_recent_slots.attributes.slots_table }}
